#!/usr/bin/env python3.10
from exceptions import ApiServiceError, CantGetCoordinates
from coordinates import get_coordinates
from weather_api_service import get_weather
from weather_formatter import format_weather


def main():
    try:
        coordinates = get_coordinates()
    except CantGetCoordinates:
        print("Can't get coordinates.")
        exit(1)
    try:
        weather = get_weather(coordinates)
    except ApiServiceError:
        print("Can't get weather forecast from API service.")
        exit(1)
    print(format_weather(weather))


if __name__ == "__main__":
    main()
